### PR TITLE
Add numpy and python-dateutil to the list of python packages

### PR DESCRIPTION
**Pull request by fernandohds564**

### CODE REVIEW

**Comment by fernandohds564** [comment]
I didn't understand that either, @lerwys. I added both of them following what is done for scipy.

**Comment by fernandohds564** [comment]
Do you want me to fix this issue for all python packages or just the ones I've added?

**Comment by lerwys** [comment]
I think we can fix just for the packages in this pull request. And later we fix for the other ones

**Comment by fernandohds564** [comment]
done @lerwys!

**Comment by lerwys** [comment]
Thanks! I think we need to further discuss where to keep these "extra" packages in the future. I'm opening an issue regarding that (#17)

**Pull request merged**
