### PR TITLE
lnls-ans-role-ntp: update script

### PR DESCRIPTION
**Pull request by xresende**
Change NTP clint config: seems to be broken with new version of NTP server.

### CODE REVIEW

**Review by anacso17 — APPROVED** [review]

**Review by edupcoelho — APPROVED** [review]

**Review by lerwys — COMMENTED** [review]
Isn't it better to use `pool` instead of `server`?

https://kb.meinbergglobal.com/kb/time_sync/ntp/configuration/ntp_pool_usage
https://www.eecis.udel.edu/~mills/ntp/html/discover.html#pool

The main benefit seems that `pool` queries the DNS for the specified server dynamically, being more robust to changes.

**Comment by xresende** [comment]
> Isn't it better to use `pool` instead of `server`?
> 
> https://kb.meinbergglobal.com/kb/time_sync/ntp/configuration/ntp_pool_usage
> https://www.eecis.udel.edu/~mills/ntp/html/discover.html#pool
> 
> The main benefit seems that `pool` queries the DNS for the specified server dynamically, being more robust to changes.

But we are using IPs for the servers, right? If we do not intend to use names instead, the simpler 'server' option actually seems more 'robust' (even though less flexible), no?

**Comment by lerwys** [comment]
I think we should always have used names instead of fixed IP addresses. But one question: does the `poll` directive work with IPs?

**Comment by lerwys** [comment]
And another thing. Maybe we should revisit the `minpoll`, `maxpoll` directives. They seem very aggressive.

**Comment by xresende** [comment]
> I think we should always have used names instead of fixed IP addresses. But one question: does the `poll` directive work with IPs? I think both directives work with both names and IPs.

we are already using fixed IP in some many things... If we agree and decide on names instead, then we could use 'poll', I think.

**Comment by xresende** [comment]
> And another thing. Maybe we should revisit the `minpoll`, `maxpoll` directives. They seem very aggressive. If I'm not mistaken we are using the fastest rate available. Do we really need that?

I dont know. do we, @edupcoelho ?

**Comment by xresende** [comment]
@lerwys , All issues you mention are minor ones, in my opinion. This PR seems to be a working, simple and fast fix [we had problems today interpreting archived data with inconsistent timestamps!]. But if someone wants to improve over this PRt, it would be nice!

**Comment by lerwys** [comment]
Sorry for being harsh, but we are always in a hurry to merge PRs without thoroughly discussing and understanding them. There's not much of a point of having reviewers if we always need to push them "right away".

**Comment by lerwys** [comment]
Anyway, I think we were supposed to achieve a few dozens of `ms` accuracy with even the default NTP configs. Maybe there is something else going on. But if this PR fixes the issue maybe there's a misunderstanding of mine about `server` and `poll` directives.

**Comment by xresende** [comment]
> Anyway, I think we were supposed to achieve a few dozens of `ms` accuracy with even the default NTP configs. Maybe there is something else going on. But if this PR fixes the issue maybe there's a misunderstanding of mine about `server` and `poll` directives.

using 'server' instead of 'poll' did synchronize all hosts. but we can investigate later why 'poll' seems to be broken with the new server config. should we create an issue?

**Review by lerwys — APPROVED** [review]
Ok. We can open a new ticket to investigate this further. I still think the minpoll/maxpoll of 3/3 is too aggressive. There seems to be a compromise between accuracy and stability in selecting this values.

Just an example of possible problems of using too short poll values: https://access.redhat.com/solutions/39194

**Review by fernandohds564 — APPROVED** [review]

**Comment by xresende** [comment]
> Ok. We can open a new ticket to investigate this further. I still think the minpoll/maxpoll of 3/3 is too aggressive. There seems to be a compromise between accuracy and stability in selecting this values.
> 
> Just an example of possible problems of using too short poll values: https://access.redhat.com/solutions/39194

I created the ticket.

**Pull request merged**
