### PR TITLE
Add texlive-full to the list of installed packages.

### PR DESCRIPTION
**Pull request by fernandohds564**
Latex is very useful to make pretty labels and texts in matplotlib figures and it is also an interesting tool for notebooks.

### CODE REVIEW

**Comment by lerwys** [comment]
Hi @fernandohds564 . Can we install just a subset of tex to get those pretty labels? I believe in most distribution texlive-full is around 2GB!

**Comment by fernandohds564** [comment]
Maybe we could @lerwys, but I don't know which sub-packages we have to install to get the symbols we need. Besides, if occasionally we try to use a different symbol, we may find out that it is not installed.
You are correct, If I'm not wrong yesterday I had to download over 4Gb of data to install this package in lnls455-linux.
Do you think this size is a problem? Our HDs are very large
If you think it is a problem I can put an extra work to this PR to find out which packages we have to install to get what we want from texlive!

**Comment by lerwys** [comment]
Well. I'm not really worried about our HDs. It's more from a maintainability point of view. Installing such large packages, with dozens of other dependencies being pulled in consequence are "worrisome". I would always suggest for us to install the minimum set of packages that solves what we need.

On my ubuntu 18 system `texlive-full` installs lots of new fonts, image conversion packages, lots of pearl scripts and even `xterm`.

We should try installing only `texlive-base` (or `texlive-latex-recommended`), `dvipng` and `ghostscript`, as it is maybe enough for matplotlib (https://matplotlib.org/tutorials/text/usetex.html).

**Comment by xresende** [comment]
I share @lerwys' worries. We have to be particularly cautious at this point since we do not yet have separated playbooks for IOC and Desktop hosts and thus, we may install packages unnecessarily in some hosts.  I think an overall reorganization of ansible configuration is a priority. Let us ask the main ansible maintainer...

**Comment by fernandohds564** [comment]
Ok @lerwys and @xresende, I changed the PR to install texlive-latex-recommended, ghostscript and dvipng, which already was in the list of packages.

**Comment by lerwys** [comment]
> I share @lerwys' worries. We have to be particularly cautious at this point since we do not yet have separated playbooks for IOC and Desktop hosts and thus we may install packages unnecessarily in some hosts. I think an overall reorganization of ansible configuration files is a priority. Let us ask the main ansible maintainer...

I also think we should better split the playbooks to allow this differentiation between IOC and Desktop hosts. This is directly related to #102, #17 and #3 and PR #123. 

I can try to start fixing the mentioned problems in #123 next week or so.

#17 would require more work and I would like to address that later or if someone would be interested in investing the time to work on that, that would be great.

**Comment by lerwys** [comment]
> Ok @lerwys and @xresende, I changed the PR to install texlive-latex-recommended, ghostscript and dvipng, which already was in the list of packages.

I think it's good now. While I'm working on #123 I will try to install these dependencies only at the Desktop PCs not on the IOC ones. Would that be ok? Or do we need Latex on those as well for some reason?

**Comment by fernandohds564** [comment]
I think we don't need it installed in the IOC PCs, @lerwys.

**Comment by xresende** [comment]
> I think we don't need it installed in the IOC PCs, @lerwys.

I agree, @lerwys

**Comment by lerwys** [comment]
OK then, @xresende , @fernandohds564 . Thanks!

**Pull request merged**
