### PR TITLE
Update ADDR_LIST

### PR DESCRIPTION
**Pull request by fernandohds564**
This PR adds the hostnames of the Kyma Undulators CLPs and RAD Thermos to the epics ADDR LIST for the role `sirius-apps`.
They are needed for the new control room, because it is in a different subnet from them.
However their addition to the ADDR LIST will not compromise the connection of the old control room with the PVs provided by these servers.
It will only show the PVs as duplicated while connecting to them.

### CODE REVIEW

**Comment by lerwys** [comment]
Are those devices on the "corporative" network? Shouldn't they be at the controls network?

**Comment by lerwys** [comment]
Also, why does the core switch "broadcast" does not work in this case? In the old control room even different subnets were reached by the EPICS broadcast by means of "broadcast forwarding".

**Comment by fernandohds564** [comment]
> Also, why does the core switch "broadcast" does not work in this case? In the old control room even different subnets were reached by the EPICS broadcast by means of "broadcast forwarding".

@edupcoelho, can you help me on this one, please?

**Comment by fernandohds564** [comment]
> Are those devices on the "corporative" network? Shouldn't they be at the controls network?

The magnet group asked to place the undulators Place in the corporative network for Kyma agents to be able to access remotely these controllers. The Thermo devices are in the corporative network because they are placed in the building experimental hall and they keep changing location.

**Review by edupcoelho — APPROVED** [review]

**Review by xresende — APPROVED** [review]

**Review by anacso17 — APPROVED** [review]

**Review by murilobalves — APPROVED** [review]

**Comment by fernandohds564** [comment]
@lerwys, @edupcoelho explained to me that this broadcast could be done for the Kyma undulators CLP. This would require to configure the core switch of this subnet to accept these broadcasts. This is possible because we are the administrators of this specific core switch. The inconvenience is that since that subnet is from corporative network we would be configuring it differently from all the other subnets administrated by TIC.

Regarding the RAD Thermo controllers, the broadcast would not be possible because they are connected to core switches administrated by TIC and their configuration is set to ignore this kind of packages.

It seems that the most adequate solution for now is to add these IPs to our ADDR_LIST. Maybe a better solution can be discussed in the future.

**Comment by lerwys** [comment]
Hi @fernandohds564 @edupcoelho . Ok, thanks for the clarification. We can think about another solution in the future.

**Review by lerwys — APPROVED** [review]

**Pull request merged**
