### PR TITLE
Pr add role network

### PR DESCRIPTION
**Pull request by lerwys**
This PR will fix the issue with multiple DNS by effectively disabling the DNS coming from the TIC VLAN. @edupcoelho had already suggested this approach. I've just created the automation means for that. Be advised that if the interface name is different than `"TIC"`, the role will fail for that host, but you can change the interface name via `defaults/main.yml`

Please, test this role (against your own computer maybe, if it runs NetworkManager) to check if you can reach the names in both our domain and internet/intranet

### CODE REVIEW

**Comment by xresende** [comment]
@lerwys e @carneirofc , do you think it is possible/useful to include creation and/or standard interface name configurations in this PR?

**Comment by lerwys** [comment]
@xresende If we can run ansible prior to these configurations (VLAN creation), absolutely. Is this possible @carneirofc ?

**Comment by xresende** [comment]
> @xresende If we can run ansible prior to these configurations (VLAN creation), absolutely. Is this possible @carneirofc ?

I have discussed the issue with @carneirofc and @ito-rafael . we decided to postpone configuring ethernet interfaces using ansible until it is finally decided how networking cabling/connection will be set. there will probably be modifications in the near future (two physical interfaces in desktop computers, instead of only one with two virtual interfaces).

**Comment by xresende** [comment]
@lerwys , @ito-rafael has changed all virtual interfaces of desktop computers in accordance with the names you used in this PR.

**Comment by lerwys** [comment]
@xresende Ok then. Merging.

**Pull request merged**
