### PR TITLE
Include cons-common dependency

### PR DESCRIPTION
**Pull request by carneirofc**
A new dependency for the pydm-opi module is required [cons-common](https://github.com/lnls-sirius/cons-common). The initial idea is to include the module as another generic dependency.

This module was also added as a git submodule inside the [pydm-opi](https://github.com/lnls-sirius/pydm-opi) repository. As for the time of this request, the task ["clone-install-repo"](https://github.com/lnls-sirius/lnls-ansible/blob/master/roles/lnls-ans-role-clone-install/tasks/clone-install-repo.yml) uses the default value for the recursive option, which is 'yes'. So we could also modify the [Makefile](https://github.com/lnls-sirius/pydm-opi/blob/master/Makefile) inside pydm-opi to install the rependency via the git module.

I was thinking something like
```
...
install: install-files clean-git
        sudo cd cons-common && sudo ./setup.py install --single-version-externally-managed --compile --force --record /dev/null
	sudo ./setup.py install --single-version-externally-managed --compile --force --record /dev/null
...
```

### CODE REVIEW

**Comment by lerwys** [comment]
Hi @carneirofc. Your PR made me realize we might have an issue with handling the installation of repositories.

From what I remember, the NFS server ([host_vars/lnlsfac-srv1](https://github.com/lnls-sirius/lnls-ansible/blob/master/host_vars/lnlsfac-srv1) was being used only as a copy of the repositories installed at the control room computers. This was request so the operators could have a reference of what was being installed to the control room computers.

So, the file [host_vars/lnlsfac-srv1](https://github.com/lnls-sirius/lnls-ansible/blob/master/host_vars/lnlsfac-srv1) would contain a list (clone_install_repos_servnfs) that would be installed via the playbook[ playbook-servnfs.yml](https://github.com/lnls-sirius/lnls-ansible/blob/master/playbook-servnfs.yml).

Conversely, for the control room computers, as nothing related to that is defined under [host_vars](https://github.com/lnls-sirius/lnls-ansible/tree/master/host_vars), neither [group_vars](https://github.com/lnls-sirius/lnls-ansible/tree/master/group_vars), the role sirius-apps will install de default repositories as defined by [lnls-ans-role-sirius-apps/defaults/main.yml](https://github.com/lnls-sirius/lnls-ansible/blob/master/roles/lnls-ans-role-sirius-apps/defaults/main.yml).

This can get out of sync pretty quickly. We must be able to define both lists of repositories from a single place (host_vars or group_vars), as it's already done for [host_vars/lnlsfac-srv1](https://github.com/lnls-sirius/lnls-ansible/blob/master/host_vars/lnlsfac-srv1) and not rely on the defaults.

So, to fix this I think we could define a single variable to define the list of repositories to be installed on all control_room computers. Also, this variable should be used by [host_vars/lnlsfac-srv1](https://github.com/lnls-sirius/lnls-ansible/blob/master/host_vars/lnlsfac-srv1) so it's always up-to-date, as well. What do you think @xresende?

**Comment by lerwys** [comment]
Hi @carneirofc,

While we look into the issue I described would it be ok with you to install the cons-common module from within your the pydm-opi Makfile?

Would the be ok with you @xresende?

**Comment by carneirofc** [comment]
Ok

> Hi @carneirofc,
> 
> While we look into the issue I described would it be ok with you to install the cons-common module from within your the pydm-opi Makfile?
> 
> Would the be ok with you @xresende?

**Comment by carneirofc** [comment]
The repo `pydm-opi` has been updated. Is it ok to merge the request? If possible, could you guys test the install procedure in a single machine before updating the whole system?

**Comment by lerwys** [comment]
Hi @carneirofc,

Nice! Let's wait for @xresende to tell us if he will be able to test it before the next deploy.

One question though. I think this `cons-common` module is only used by `pydm-opi`, right? But when more repositories start using them how are we planning on keeping `cons-commons` versions separate for each one of the repositories, assuming we don't want all of them to be tied to a specific version at a given time?

From what I could understand you are installing `cons-common` globally for all users inside that host. 

Even if we include `cons-common` as a generic host dependency, as it was the first idea here (https://github.com/lnls-sirius/lnls-ansible/pull/123/commits/a592e88ae66d3e7d3ae53777b8eb4006626c2447), is it enough to have a single version of `cons-common` for all of the repositories or do we need different versions for  each one?

Sorry if maybe I'm complicating the issue more than i should. It's just that keeping everything consistent can be a lot of trouble later on. Maybe a simple solution is to use conda if that's the case?

**Comment by xresende** [comment]
@carneirofc , @lerwys , I will try this PR as it is in our deploy today. But let us keep discussing it and other ansible issues. At this moment that are a few issues that we have been circumventing in order to use the tool. I will try to get in touch with you two and discuss them. I need help.

**Comment by lerwys** [comment]
I'm closing this as it's out of date. This will be fixed on a new PR, coming soon and will be tracked by issue #176

**Pull request closed without merging**
