### PR TITLE
Update IP list

### PR DESCRIPTION
**Pull request by fernandohds564**
- remove deprecated Linac IPs from old IBM server with motherboard problems;
- remove RAD Thermo IPs to avoid error messages from epics for any interaction with arbitrary PVs, when these devices are not connected to the network.

### CODE REVIEW

**Comment by fernandohds564** [comment]
@lerwys, is it normal to fail at lint checks?

**Comment by lerwys** [comment]
Hum... That's because of a previous PR that imported the `docker` role. Even though it's a third party role it might be interesting to fix that in our repository.

**Review by lerwys — APPROVED** [review]

**Comment by fernandohds564** [comment]
humm, ok. But can we do it in another PR or do you think it is better if I do it now, in this one?

**Comment by lerwys** [comment]
I think it's better if we do it outside of this PR, as it's unrelated to your modifications.

**Review by xresende — APPROVED** [review]

**Pull request merged**
